"""
Wiki Compiler - Incrementally compiles raw sources into wiki articles.
Uses LLM to generate summaries and concept articles.
"""
from typing import Dict, List, Optional, Any
from pathlib import Path
from datetime import datetime

from ..core.client import OllamaClient
from ..tools.safe_io import SafeIO
from .indexer import WikiIndexer


class WikiCompiler:
    """Compiles raw documents into wiki structure."""
    
    def __init__(self, data_dir: str, llm_host: str = "http://localhost:11434"):
        self.io = SafeIO(data_dir)
        self.indexer = WikiIndexer(data_dir)
        self.llm = OllamaClient(host=llm_host)
        
        self.raw_dir = "raw"
        self.wiki_dir = "wiki"
    
    def _extract_title(self, content: str) -> str:
        """Extract title from markdown (first heading or filename)."""
        lines = content.split("\n")
        for line in lines[:10]:
            if line.startswith("# "):
                return line[2:].strip()
        return "Untitled"
    
    def _generate_summary(self, content: str, filename: str) -> str:
        """Use LLM to generate a concise summary."""
        prompt = f"""Summarize this document in 2-3 sentences. Focus on key concepts and findings.

Document: {filename}
Content:
{content[:1500]}

Summary:"""
        
        try:
            summary = self.llm.generate(prompt, mode="GENERAL")
            return summary.strip()
        except Exception as e:
            return f"Summary generation failed: {e}"
    
    def _extract_concepts(self, content: str, summary: str) -> List[str]:
        """Use LLM to extract key concepts as a comma-separated list."""
        prompt = f"""Extract 3-5 key concepts from this text. Return ONLY a comma-separated list of concepts.

Content:
{content[:1000]}

Summary:
{summary}

Concepts:"""
        
        try:
            response = self.llm.generate(prompt, mode="OFFICE")
            # Parse comma-separated list
            concepts = [c.strip() for c in response.split(",")]
            return [c for c in concepts if c and len(c) > 2][:5]
        except Exception:
            # Fallback: use simple keyword extraction
            return ["general", "concept"]
    
    def _find_internal_links(self, content: str) -> List[str]:
        """Find markdown links to other wiki pages."""
        import re
        pattern = r'\[\[([^\]]+)\]\]'  # [[Page Name]] style
        matches = re.findall(pattern, content)
        return matches
    
    def compile_file(self, raw_path: str) -> Optional[Dict[str, Any]]:
        """Compile a single raw file into wiki format."""
        if not self.io.exists(raw_path):
            return None
        
        # Check if already compiled and newer
        filename = Path(raw_path).name
        wiki_path = f"{self.wiki_dir}/{Path(raw_path).stem}.md"
        
        raw_mtime = self.io.get_mtime(raw_path)
        wiki_mtime = self.io.get_mtime(wiki_path) if self.io.exists(wiki_path) else 0
        
        if wiki_mtime > raw_mtime:
            print(f"Skipping {filename} (already up-to-date)")
            return None
        
        # Read raw content
        content = self.io.read_text(raw_path)
        
        # Extract metadata
        title = self._extract_title(content)
        print(f"Compiling: {title}")
        
        # Generate summary
        summary = self._generate_summary(content, filename)
        
        # Extract concepts
        concepts = self._extract_concepts(content, summary)
        
        # Create wiki article
        wiki_content = f"""# {title}

**Source:** `{filename}`  
**Compiled:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Summary

{summary}

## Key Concepts

{', '.join(f'[[{c}]]' for c in concepts)}

## Content

{content}

---
*Auto-generated by COM Wiki Compiler*
"""
        
        # Write wiki article
        self.io.write_text(wiki_path, wiki_content)
        
        # Update index
        word_count = len(content.split())
        self.indexer.add_document(
            path=wiki_path,
            title=title,
            summary=summary,
            concepts=concepts,
            word_count=word_count
        )
        
        # Add backlinks for internal links
        internal_links = self._find_internal_links(content)
        for link in internal_links:
            target_path = f"{self.wiki_dir}/{link.replace(' ', '_')}.md"
            self.indexer.add_backlink(wiki_path, target_path)
        
        return {
            "raw": raw_path,
            "wiki": wiki_path,
            "title": title,
            "concepts": concepts
        }
    
    def compile_all(self, incremental: bool = True) -> List[Dict[str, Any]]:
        """Compile all raw files incrementally."""
        results = []
        
        # Ensure directories exist
        self.io.ensure_dir(self.wiki_dir)
        
        # Get all raw files
        raw_files = self.io.list_files(self.raw_dir, "*")
        
        if not raw_files:
            print("No raw files found to compile")
            return results
        
        print(f"Found {len(raw_files)} raw files to process")
        
        for raw_path in raw_files:
            result = self.compile_file(raw_path) if incremental else self.compile_file(raw_path)
            if result:
                results.append(result)
        
        print(f"Compiled {len(results)} files")
        return results
    
    def create_concept_article(self, concept: str) -> Optional[str]:
        """Create a concept article by aggregating related documents."""
        docs = self.indexer.get_concept_documents(concept)
        
        if not docs:
            return None
        
        wiki_path = f"{self.wiki_dir}/concepts/{concept.replace(' ', '_')}.md"
        
        # Skip if exists
        if self.io.exists(wiki_path):
            return wiki_path
        
        # Aggregate content
        aggregated = "\n\n".join([
            f"From [[{doc['title']}]]:\n{doc['summary']}"
            for doc in docs[:5]  # Limit to 5 docs
        ])
        
        # Generate concept definition
        prompt = f"""Define the concept "{concept}" based on these related summaries:

{aggregated}

Write a clear, concise definition (2-3 paragraphs) explaining what {concept} means in this context."""
        
        try:
            definition = self.llm.generate(prompt, mode="GENERAL")
        except Exception:
            definition = f"*Definition of {concept} pending*"
        
        # Create article
        content = f"""# {concept}

## Definition

{definition}

## Related Documents

{chr(10).join(f"- [[{doc['title']}]]" for doc in docs)}

---
*Auto-generated concept article*
"""
        
        self.io.write_text(wiki_path, content)
        self.indexer.add_document(
            path=wiki_path,
            title=concept,
            summary=definition[:200],
            concepts=[concept],
            word_count=len(content.split())
        )
        
        return wiki_path
