"""
Godot Engine Harness - Run function for signal execution
Generates GDScript code based on signal payload
"""

from .godot_engine import GodotEngineTool

def run(payload: str) -> str:
    """
    Execute Godot signal and generate GDScript code
    
    Payload format: template_name:params
    Examples:
      - player_movement_2d
      - enemy_ai:patrol
      - inventory_system
    """
    tool = GodotEngineTool()
    
    # Parse payload
    parts = payload.split(':')
    template = parts[0] if parts else "basic_script"
    params = parts[1] if len(parts) > 1 else ""
    
    # Map templates to actions
    if "player" in template.lower() or "mov" in template.lower():
        result = tool.execute("find_demo_pattern", mechanic="player_controller")
        code = _generate_player_code(params)
    elif "enemy" in template.lower() or "ai" in template.lower():
        result = tool.execute("find_demo_pattern", mechanic="enemy_ai")
        code = _generate_enemy_code(params)
    elif "inventory" in template.lower():
        code = _generate_inventory_code()
    elif "shader" in template.lower():
        result = tool.execute("generate_shader_snippet", effect=params or "outline")
        code = result.get('shader', "# Shader code not available")
    else:
        # Generic GDScript template
        code = _generate_generic_code(template, params)
    
    return f"🎮 GDScript generated:\n\n```gdscript\n{code}\n```"

def _generate_player_code(params: str) -> str:
    """Generate 2D player movement code"""
    return """extends CharacterBody2D

@export var speed = 300.0
@export var jump_velocity = -400.0

# Get the gravity from the project settings to be synced with RigidBody nodes.
var gravity = ProjectSettings.get_setting("physics/2d/default_gravity")

func _physics_process(delta):
    # Add the gravity.
    if not is_on_floor():
        velocity.y += gravity * delta

    # Handle jump.
    if Input.is_action_just_pressed("ui_accept") and is_on_floor():
        velocity.y = jump_velocity

    # Get the input direction and handle the movement/deceleration.
    var direction = Input.get_axis("ui_left", "ui_right")
    if direction:
        velocity.x = direction * speed
    else:
        velocity.x = move_toward(velocity.x, 0, speed)

    move_and_slide()
"""

def _generate_enemy_code(params: str) -> str:
    """Generate enemy AI code"""
    patrol_type = params if params else "patrol"
    return f"""extends CharacterBody2D

@export var speed = 150.0
@export var patrol_points: Array[Vector2] = [Vector2(-200, 0), Vector2(200, 0)]
var current_point_index = 0
var state = "{patrol_type}"

func _physics_process(delta):
    if patrol_points.size() == 0:
        return
    
    var target = patrol_points[current_point_index]
    var direction = (target - global_position).normalized()
    
    if global_position.distance_to(target) < 10:
        current_point_index = (current_point_index + 1) % patrol_points.size()
    
    velocity = direction * speed
    move_and_slide()
"""

def _generate_inventory_code() -> str:
    """Generate inventory system code"""
    return """extends Node

class InventoryItem:
    var name: String
    var quantity: int
    var icon: Texture2D
    
    func _init(item_name: String, qty: int = 1):
        name = item_name
        quantity = qty

var items: Array[InventoryItem] = []

func add_item(item_name: String, quantity: int = 1):
    for item in items:
        if item.name == item_name:
            item.quantity += quantity
            return
    items.append(InventoryItem.new(item_name, quantity))

func remove_item(item_name: String, quantity: int = 1) -> bool:
    for item in items:
        if item.name == item_name:
            item.quantity -= quantity
            if item.quantity <= 0:
                items.erase(item)
            return true
    return false

func has_item(item_name: String, quantity: int = 1) -> bool:
    for item in items:
        if item.name == item_name and item.quantity >= quantity:
            return true
    return false
"""

def _generate_generic_code(template: str, params: str) -> str:
    """Generate generic GDScript template"""
    class_name = template.replace("_", " ").title().replace(" ", "")
    return f"""extends Node
# {template} - Generated by COM v4

# Called when the node enters the scene tree for the first time.
func _ready():
    pass

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
    pass
"""

if __name__ == "__main__":
    # Test
    print(run("player_movement_2d"))
    print("\n" + "="*60 + "\n")
    print(run("enemy_ai:patrol"))
