"""
Wiki Compiler - KNOWLEDGE CORE for COM v3
Incrementally compiles raw sources into wiki articles with backlinks.
Uses LLM to generate summaries and concept articles.

Division of Labor:
- Python (this module): File I/O, ingestion, compilation, indexing
- LLM: Only refines summaries and resolves ambiguities
"""
from typing import Dict, List, Optional, Any
from pathlib import Path
from datetime import datetime
import re

from core.com_core import OllamaClient
from tools.safe_io import SafeIO
from tools.data_ops.wiki_indexer import WikiIndexer


class WikiCompiler:
    """Compiles raw documents into wiki structure."""

    def __init__(self, data_dir: str = "data", llm_host: str = "http://localhost:11434"):
        self.io = SafeIO(data_dir)
        self.indexer = WikiIndexer(data_dir)
        self.llm = OllamaClient(host=llm_host)

        self.raw_dir = "raw"
        self.wiki_dir = "wiki"

    def _extract_title(self, content: str) -> str:
        """Extract title from markdown (first heading or filename)."""
        lines = content.split("\n")
        for line in lines[:10]:
            if line.startswith("# "):
                return line[2:].strip()
        return "Untitled"

    def _generate_summary(self, content: str, filename: str) -> str:
        """Use LLM to generate a concise summary (2-3 sentences)."""
        prompt = f"""Summarize this document in 2-3 sentences. Focus on key concepts and findings.

Document: {filename}
Content:
{content[:1500]}

Summary:"""

        try:
            summary = self.llm.generate(prompt, mode="GENERAL")
            return summary.strip()
        except Exception as e:
            return f"Summary generation failed: {e}"

    def _extract_concepts(self, content: str, summary: str) -> List[str]:
        """Use LLM to extract key concepts as a comma-separated list."""
        prompt = f"""Extract 3-5 key concepts from this text. Return ONLY a comma-separated list of concepts.

Content:
{content[:1000]}

Summary:
{summary}

Concepts:"""

        try:
            response = self.llm.generate(prompt, mode="OFFICE")
            # Parse comma-separated list
            concepts = [c.strip() for c in response.split(",")]
            return [c for c in concepts if c and len(c) > 2][:5]
        except Exception:
            # Fallback: use simple keyword extraction
            return ["general", "concept"]

    def _find_internal_links(self, content: str) -> List[str]:
        """Find markdown links to other wiki pages ([[Page Name]] style)."""
        pattern = r'\[\[([^\]]+)\]\]'  # [[Page Name]] style
        matches = re.findall(pattern, content)
        return matches

    def compile_file(self, raw_path: str) -> Optional[Dict[str, Any]]:
        """Compile a single raw file into wiki format."""
        if not self.io.exists(raw_path):
            return None

        # Check if already compiled and newer
        filename = Path(raw_path).name
        wiki_path = f"{self.wiki_dir}/{Path(raw_path).stem}.md"

        raw_mtime = self.io.get_mtime(raw_path)
        wiki_mtime = self.io.get_mtime(wiki_path) if self.io.exists(wiki_path) else 0

        if wiki_mtime > raw_mtime:
            print(f"Skipping {filename} (already up-to-date)")
            return None

        # Read raw content
        content = self.io.read_text(raw_path)

        # Extract metadata
        title = self._extract_title(content)
        print(f"Compiling: {title}")

        # Generate summary
        summary = self._generate_summary(content, filename)

        # Extract concepts
        concepts = self._extract_concepts(content, summary)

        # Create wiki article
        wiki_content = f"""# {title}

**Source:** `{filename}`
**Compiled:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Summary

{summary}

## Key Concepts

{', '.join(f'[[{c}]]' for c in concepts)}

## Content

{content}

---
*Auto-generated by COM Wiki Compiler*
"""

        # Write wiki article
        self.io.write_text(wiki_path, wiki_content)

        # Update index
        word_count = len(content.split())
        self.indexer.add_document(
            path=wiki_path,
            title=title,
            summary=summary,
            concepts=concepts,
            word_count=word_count
        )

        # Add backlinks for internal links
        # FIXED: Now uses consistent doc_id format via indexer.add_backlink
        internal_links = self._find_internal_links(content)
        for link in internal_links:
            target_path = f"{self.wiki_dir}/{link.replace(' ', '_')}.md"
            self.indexer.add_backlink(wiki_path, target_path)

        return {
            "raw": raw_path,
            "wiki": wiki_path,
            "title": title,
            "concepts": concepts
        }

    def compile_all(self, incremental: bool = True) -> List[Dict[str, Any]]:
        """Compile all raw files incrementally."""
        results = []

        # Ensure directories exist
        self.io.ensure_dir(self.wiki_dir)

        # Get all raw files
        raw_files = self.io.list_files(self.raw_dir, "*")

        if not raw_files:
            print("No raw files found to compile")
            return results

        print(f"Found {len(raw_files)} raw files to process")

        for raw_path in raw_files:
            result = self.compile_file(raw_path) if incremental else self.compile_file(raw_path)
            if result:
                results.append(result)

        print(f"Compiled {len(results)} files")
        return results

    def create_concept_article(self, concept: str) -> Optional[str]:
        """Create a concept article by aggregating related documents."""
        docs = self.indexer.get_concept_documents(concept)

        if not docs:
            return None

        wiki_path = f"{self.wiki_dir}/concepts/{concept.replace(' ', '_')}.md"

        # Skip if exists
        if self.io.exists(wiki_path):
            return wiki_path

        # Aggregate content
        aggregated = "\n\n".join([
            f"From [[{doc['title']}]]:\n{doc['summary']}"
            for doc in docs[:5]  # Limit to 5 docs
        ])

        # Generate concept definition
        prompt = f"""Define the concept "{concept}" based on these related summaries:

{aggregated}

Write a clear, concise definition (2-3 paragraphs) explaining what {concept} means in this context."""

        try:
            definition = self.llm.generate(prompt, mode="GENERAL")
        except Exception:
            definition = f"*Definition of {concept} pending*"

        # Create article
        content = f"""# {concept}

## Definition

{definition}

## Related Documents

{chr(10).join(f"- [[{doc['title']}]]" for doc in docs)}

---
*Auto-generated concept article*
"""

        self.io.write_text(wiki_path, content)
        self.indexer.add_document(
            path=wiki_path,
            title=concept,
            summary=definition[:200],
            concepts=[concept],
            word_count=len(content.split())
        )

        return wiki_path


class WikiRetriever:
    """
    TF-IDF based search for wiki content.
    No embeddings, no external models - just pure term frequency.
    Used by com_chat.py to retrieve relevant wiki snippets before LLM answers.
    """

    def __init__(self, data_dir: str):
        self.io = SafeIO(data_dir)
        self.documents: Dict[str, str] = {}  # path -> content
        self.idf: Dict[str, float] = {}
        self._loaded = False

    def _tokenize(self, text: str) -> List[str]:
        """Simple tokenization: lowercase, remove punctuation."""
        text = text.lower()
        tokens = re.findall(r'\b[a-z]+\b', text)
        # Remove common stopwords
        stopwords = {
            'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
            'of', 'with', 'by', 'from', 'is', 'are', 'was', 'were', 'be', 'been',
            'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would',
            'could', 'should', 'may', 'might', 'must', 'shall', 'can', 'need',
            'it', 'its', 'this', 'that', 'these', 'those', 'i', 'you', 'he',
            'she', 'we', 'they', 'what', 'which', 'who', 'whom', 'whose'
        }
        return [t for t in tokens if t not in stopwords and len(t) > 2]

    def load_wiki(self) -> None:
        """Load all wiki markdown files."""
        self.documents = {}

        try:
            md_files = self.io.list_files("wiki", "*.md")

            for path in md_files:
                if path == "wiki/_index.md":  # Skip index if exists
                    continue

                try:
                    content = self.io.read_text(path)
                    # Store first 2000 chars for speed (adjust as needed)
                    self.documents[path] = content[:2000]
                except Exception:
                    continue

            self._compute_idf()
            self._loaded = True

        except Exception:
            self._loaded = False

    def _compute_idf(self) -> None:
        """Compute IDF scores for all terms."""
        if not self.documents:
            return

        n_docs = len(self.documents)
        doc_freq: dict = {}

        # Count document frequency for each term
        for content in self.documents.values():
            tokens = set(self._tokenize(content))
            for token in tokens:
                doc_freq[token] = doc_freq.get(token, 0) + 1

        # Compute IDF: log(N / df)
        from math import log10
        self.idf = {
            term: log10(n_docs / freq) if freq > 0 else 0
            for term, freq in doc_freq.items()
        }

    def search(self, query: str, top_k: int = 5) -> List[tuple]:
        """
        Search wiki for query.
        Returns list of (path, snippet, score).
        """
        if not self._loaded:
            self.load_wiki()

        if not self.documents:
            return []

        query_tokens = self._tokenize(query)
        if not query_tokens:
            return []

        scores: Dict[str, float] = {}

        # Compute TF-IDF score for each document
        for path, content in self.documents.items():
            doc_tokens = self._tokenize(content)
            if not doc_tokens:
                continue

            # Term frequency in document
            from collections import Counter
            tf = Counter(doc_tokens)
            max_tf = max(tf.values()) if tf else 1

            # Compute score
            score = 0.0
            for token in query_tokens:
                if token in tf and token in self.idf:
                    # Normalized TF * IDF
                    score += (tf[token] / max_tf) * self.idf[token]

            if score > 0:
                scores[path] = score

        # Sort by score descending
        sorted_results = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:top_k]

        # Return with snippets
        results = []
        for path, score in sorted_results:
            content = self.documents[path]
            # Extract relevant snippet (first 200 chars for preview)
            snippet = content[:200].replace("\n", " ").strip() + "..."
            results.append((path, snippet, score))

        return results

    def get_related(self, path: str, top_k: int = 3) -> List[tuple]:
        """Find documents related to a given document."""
        if not self._loaded:
            self.load_wiki()

        if path not in self.documents:
            return []

        # Use document's own tokens as query
        content = self.documents[path]
        tokens = self._tokenize(content)

        # Get top terms in this document
        from collections import Counter
        term_freq = Counter(tokens)
        top_terms = [term for term, _ in term_freq.most_common(10)]

        # Search using top terms
        query = " ".join(top_terms)
        results = self.search(query, top_k=top_k + 1)

        # Filter out the original document
        return [(p, s) for p, _, s in results if p != path][:top_k]
