"""
Wiki Compiler - KNOWLEDGE CORE for COM v3
Incrementally compiles raw sources into wiki articles with backlinks.
Uses LLM to generate summaries and concept articles.

Division of Labor:
- Python (this module): File I/O, ingestion, compilation, indexing
- LLM: Only refines summaries and resolves ambiguities
"""
import logging
import json
from typing import Dict, List, Optional, Any
from pathlib import Path
from datetime import datetime
import re
from dataclasses import dataclass

from core.com_core import OllamaClient
from tools.safe_io import SafeIO
from tools.data_ops.wiki_indexer import WikiIndexer


@dataclass
class HealthIssue:
    """Represents a health check issue found in the wiki."""
    type: str  # 'orphaned_backlink', 'missing_summary', 'broken_link'
    severity: str  # 'low', 'medium', 'high'
    document: str
    message: str
    details: Optional[Dict] = None


class WikiCompiler:
    """Compiles raw documents into wiki structure."""

    def __init__(self, data_dir: str = "data", llm_host: str = "http://localhost:11434", wiki_dir: str = None):
        # Support both data_dir and wiki_dir parameter names for backward compatibility
        if wiki_dir is not None and data_dir == "data":
            data_dir = str(Path(wiki_dir).parent)
        
        self.io = SafeIO(data_dir)
        self.indexer = WikiIndexer(data_dir)
        # Lazy load LLM client only when needed
        self._llm = None
        self._llm_host = llm_host

        self.raw_dir = "raw"
        self.wiki_dir = "wiki"
    
    @property
    def llm(self):
        """Lazy load LLM client."""
        if self._llm is None:
            from core.com_core import OllamaClient
            self._llm = OllamaClient()
        return self._llm

    def _extract_title(self, content: str) -> str:
        """Extract title from markdown (first heading or filename)."""
        lines = content.split("\n")
        for line in lines[:10]:
            if line.startswith("# "):
                return line[2:].strip()
        return "Untitled"

    def _generate_summary(self, content: str, filename: str) -> str:
        """Use LLM to generate a concise summary (2-3 sentences)."""
        prompt = f"""Summarize this document in 2-3 sentences. Focus on key concepts and findings.

Document: {filename}
Content:
{content[:1500]}

Summary:"""

        try:
            summary = self.llm.generate(prompt, mode="GENERAL")
            return summary.strip()
        except Exception as e:
            return f"Summary generation failed: {e}"

    def _extract_concepts(self, content: str, summary: str) -> List[str]:
        """Use LLM to extract key concepts as a comma-separated list."""
        prompt = f"""Extract 3-5 key concepts from this text. Return ONLY a comma-separated list of concepts.

Content:
{content[:1000]}

Summary:
{summary}

Concepts:"""

        try:
            response = self.llm.generate(prompt, mode="OFFICE")
            # Parse comma-separated list
            concepts = [c.strip() for c in response.split(",")]
            return [c for c in concepts if c and len(c) > 2][:5]
        except Exception:
            # Fallback: use simple keyword extraction
            return ["general", "concept"]

    def _find_internal_links(self, content: str) -> List[str]:
        """Find markdown links to other wiki pages ([[Page Name]] style)."""
        pattern = r'\[\[([^\]]+)\]\]'  # [[Page Name]] style
        matches = re.findall(pattern, content)
        return matches

    def compile_file(self, raw_path: str) -> Optional[Dict[str, Any]]:
        """Compile a single raw file into wiki format."""
        if not self.io.exists(raw_path):
            return None

        # Check if already compiled and newer
        filename = Path(raw_path).name
        wiki_path = f"{self.wiki_dir}/{Path(raw_path).stem}.md"

        raw_mtime = self.io.get_mtime(raw_path)
        wiki_mtime = self.io.get_mtime(wiki_path) if self.io.exists(wiki_path) else 0

        if wiki_mtime > raw_mtime:
            print(f"Skipping {filename} (already up-to-date)")
            return None

        # Read raw content
        content = self.io.read_text(raw_path)

        # Extract metadata
        title = self._extract_title(content)
        print(f"Compiling: {title}")

        # Generate summary
        summary = self._generate_summary(content, filename)

        # Extract concepts
        concepts = self._extract_concepts(content, summary)

        # Create wiki article
        wiki_content = f"""# {title}

**Source:** `{filename}`
**Compiled:** {datetime.now().strftime("%Y-%m-%d %H:%M")}

## Summary

{summary}

## Key Concepts

{', '.join(f'[[{c}]]' for c in concepts)}

## Content

{content}

---
*Auto-generated by COM Wiki Compiler*
"""

        # Write wiki article
        self.io.write_text(wiki_path, wiki_content)

        # Update index
        word_count = len(content.split())
        self.indexer.add_document(
            path=wiki_path,
            title=title,
            summary=summary,
            concepts=concepts,
            word_count=word_count
        )

        # Add backlinks for internal links
        # FIXED: Now uses consistent doc_id format via indexer.add_backlink
        internal_links = self._find_internal_links(content)
        for link in internal_links:
            target_path = f"{self.wiki_dir}/{link.replace(' ', '_')}.md"
            self.indexer.add_backlink(wiki_path, target_path)

        return {
            "raw": raw_path,
            "wiki": wiki_path,
            "title": title,
            "concepts": concepts
        }

    def compile_all(self, incremental: bool = True) -> List[Dict[str, Any]]:
        """Compile all raw files incrementally."""
        results = []

        # Ensure directories exist
        self.io.ensure_dir(self.wiki_dir)

        # Get all raw files
        raw_files = self.io.list_files(self.raw_dir, "*")

        if not raw_files:
            print("No raw files found to compile")
            return results

        print(f"Found {len(raw_files)} raw files to process")

        for raw_path in raw_files:
            if incremental:
                result = self.compile_file(raw_path)
            else:
                # Force mode: delete existing wiki output before compiling
                wiki_filename = raw_path.replace('.txt', '.md').replace('.raw', '.md')
                wiki_path = f"{self.wiki_dir}/{wiki_filename}"
                if self.io.exists(wiki_path):
                    self.io.delete(wiki_path)
                result = self.compile_file(raw_path)
            if result:
                results.append(result)

        print(f"Compiled {len(results)} files")
        return results

    def create_concept_article(self, concept: str) -> Optional[str]:
        """Create a concept article by aggregating related documents."""
        docs = self.indexer.get_concept_documents(concept)

        if not docs:
            return None

        wiki_path = f"{self.wiki_dir}/concepts/{concept.replace(' ', '_')}.md"

        # Skip if exists
        if self.io.exists(wiki_path):
            return wiki_path

        # Aggregate content
        aggregated = "\n\n".join([
            f"From [[{doc['title']}]]:\n{doc['summary']}"
            for doc in docs[:5]  # Limit to 5 docs
        ])

        # Generate concept definition
        prompt = f"""Define the concept "{concept}" based on these related summaries:

{aggregated}

Write a clear, concise definition (2-3 paragraphs) explaining what {concept} means in this context."""

        try:
            definition = self.llm.generate(prompt, mode="GENERAL")
        except Exception:
            definition = f"*Definition of {concept} pending*"

        # Create article
        content = f"""# {concept}

## Definition

{definition}

## Related Documents

{chr(10).join(f"- [[{doc['title']}]]" for doc in docs)}

---
*Auto-generated concept article*
"""

        self.io.write_text(wiki_path, content)
        self.indexer.add_document(
            path=wiki_path,
            title=concept,
            summary=definition[:200],
            concepts=[concept],
            word_count=len(content.split())
        )

        return wiki_path


class WikiRetriever:
    """
    TF-IDF based search for wiki content.
    No embeddings, no external models - just pure term frequency.
    Used by com_chat.py to retrieve relevant wiki snippets before LLM answers.
    """

    def __init__(self, data_dir: str):
        self.io = SafeIO(data_dir)
        self.documents: Dict[str, str] = {}  # path -> content
        self.idf: Dict[str, float] = {}
        self._loaded = False

    def _tokenize(self, text: str) -> List[str]:
        """Simple tokenization: lowercase, remove punctuation."""
        text = text.lower()
        tokens = re.findall(r'\b[a-z]+\b', text)
        # Remove common stopwords
        stopwords = {
            'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
            'of', 'with', 'by', 'from', 'is', 'are', 'was', 'were', 'be', 'been',
            'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will', 'would',
            'could', 'should', 'may', 'might', 'must', 'shall', 'can', 'need',
            'it', 'its', 'this', 'that', 'these', 'those', 'i', 'you', 'he',
            'she', 'we', 'they', 'what', 'which', 'who', 'whom', 'whose'
        }
        return [t for t in tokens if t not in stopwords and len(t) > 2]

    def load_wiki(self) -> None:
        """Load all wiki markdown files from root and wiki/ subdirectory."""
        self.documents = {}
        self.snippets = {}  # Store short snippets for display

        try:
            # Try both root directory and wiki/ subdirectory
            md_files = []
            
            # First try wiki/ subdirectory
            try:
                md_files.extend(self.io.list_files("wiki", "*.md"))
            except Exception:
                pass
            
            # Also check root directory for .md files
            try:
                root_files = self.io.list_files(".", "*.md")
                # Filter out any that might be in subdirectories already counted
                for f in root_files:
                    if f not in md_files and '/' not in f:
                        md_files.append(f)
            except Exception:
                pass

            for path in md_files:
                if path.endswith("_index.md"):  # Skip index if exists
                    continue

                try:
                    content = self.io.read_text(path)
                    # Store full content for TF-IDF indexing
                    self.documents[path] = content
                    # Store first 200 chars for display snippets
                    self.snippets[path] = content[:200].replace("\n", " ").strip() + "..."
                except Exception:
                    continue

            self._compute_idf()
            self._loaded = True

        except Exception:
            self._loaded = False

    def _compute_idf(self) -> None:
        """Compute IDF scores for all terms."""
        if not self.documents:
            return

        n_docs = len(self.documents)
        doc_freq: dict = {}

        # Count document frequency for each term
        for content in self.documents.values():
            tokens = set(self._tokenize(content))
            for token in tokens:
                doc_freq[token] = doc_freq.get(token, 0) + 1

        # Compute IDF: log(N / df)
        from math import log10
        self.idf = {
            term: log10(n_docs / freq) if freq > 0 else 0
            for term, freq in doc_freq.items()
        }

    def search(self, query: str, top_k: int = 5) -> List[tuple]:
        """
        Search wiki for query.
        Returns list of (path, snippet, score).
        """
        if not self._loaded:
            self.load_wiki()

        if not self.documents:
            return []

        query_tokens = self._tokenize(query)
        if not query_tokens:
            return []

        scores: Dict[str, float] = {}

        # Compute TF-IDF score for each document
        for path, content in self.documents.items():
            doc_tokens = self._tokenize(content)
            if not doc_tokens:
                continue

            # Term frequency in document
            from collections import Counter
            tf = Counter(doc_tokens)
            max_tf = max(tf.values()) if tf else 1

            # Compute score
            score = 0.0
            for token in query_tokens:
                if token in tf and token in self.idf:
                    # Normalized TF * IDF
                    score += (tf[token] / max_tf) * self.idf[token]

            if score > 0:
                scores[path] = score

        # Sort by score descending
        sorted_results = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:top_k]

        # Return with snippets
        results = []
        for path, score in sorted_results:
            content = self.documents[path]
            # Extract relevant snippet (first 200 chars for preview)
            snippet = content[:200].replace("\n", " ").strip() + "..."
            results.append((path, snippet, score))

        return results

    def get_related(self, path: str, top_k: int = 3) -> List[tuple]:
        """Find documents related to a given document."""
        if not self._loaded:
            self.load_wiki()

        if path not in self.documents:
            return []

        # Use document's own tokens as query
        content = self.documents[path]
        tokens = self._tokenize(content)

        # Get top terms in this document
        from collections import Counter
        term_freq = Counter(tokens)
        top_terms = [term for term, _ in term_freq.most_common(10)]

        # Search using top terms
        query = " ".join(top_terms)
        results = self.search(query, top_k=top_k + 1)

        # Filter out the original document
        return [(p, s) for p, _, s in results if p != path][:top_k]

    def format_context(self, results: List[tuple]) -> str:
        """Format search results as context string for LLM."""
        if not results:
            return ""
        
        formatted_parts = []
        for path, snippet, score in results:
            formatted_parts.append(f"[{path}]: {snippet} (relevance: {score:.2f})")
        
        return "\n\n".join(formatted_parts)


class HealthChecker:
    """
    Lightweight health checker for wiki integrity.
    Designed for low-RAM environments with minimal overhead.
    
    Checks:
    - Orphaned backlinks (links to non-existent documents)
    - Missing summaries in indexed documents
    - Broken internal links [[Document Name]]
    """
    
    def __init__(self, wiki_dir: str):
        self.wiki_dir = Path(wiki_dir)
        self.io = SafeIO(str(self.wiki_dir.parent))
    
    async def run_integrity_check(self) -> List[Dict[str, Any]]:
        """
        Run complete integrity check.
        Returns list of issues found with severity levels.
        """
        issues = []
        
        # Check 1: Find orphaned backlinks
        orphan_issues = await self._check_orphaned_backlinks()
        issues.extend(orphan_issues)
        
        # Check 2: Find missing summaries
        missing_summary_issues = await self._check_missing_summaries()
        issues.extend(missing_summary_issues)
        
        # Check 3: Find broken internal links
        broken_link_issues = await self._check_broken_links()
        issues.extend(broken_link_issues)
        
        return issues
    
    async def _check_orphaned_backlinks(self) -> List[Dict[str, Any]]:
        """
        Check for backlinks pointing to non-existent documents.
        Lightweight: Only checks index metadata, not full content.
        """
        issues = []
        
        try:
            # Load indexer to get all backlinks
            indexer = WikiIndexer(str(self.wiki_dir.parent))
            
            # Get all documents from index
            documents = indexer.index.get("documents", {})
            
            # Collect all backlink targets
            all_doc_ids = set(documents.keys())
            
            for doc_id, doc_data in documents.items():
                backlinks = doc_data.get("backlinks", [])
                for backlink_target in backlinks:
                    # Extract target doc_id from path
                    target_path = Path(backlink_target)
                    target_id = target_path.stem
                    
                    if target_id not in all_doc_ids:
                        issues.append({
                            "type": "orphaned_backlink",
                            "source_doc": doc_id,
                            "target_doc": target_id,
                            "severity": "medium",
                            "message": f"Document '{doc_id}' has backlink to non-existent '{target_id}'"
                        })
        except Exception as e:
            issues.append({
                "type": "check_error",
                "severity": "high",
                "message": f"Orphaned backlink check failed: {e}"
            })
        
        return issues
    
    async def _check_missing_summaries(self) -> List[Dict[str, Any]]:
        """
        Check for documents missing summaries.
        Lightweight: Only checks index metadata.
        """
        issues = []
        
        try:
            indexer = WikiIndexer(str(self.wiki_dir.parent))
            documents = indexer.index.get("documents", {})
            
            for doc_id, doc_data in documents.items():
                summary = doc_data.get("summary", "")
                
                if not summary or summary.strip() == "":
                    issues.append({
                        "type": "missing_summary",
                        "document": doc_id,
                        "severity": "low",
                        "message": f"Document '{doc_id}' is missing a summary"
                    })
        except Exception as e:
            issues.append({
                "type": "check_error",
                "severity": "high",
                "message": f"Missing summary check failed: {e}"
            })
        
        return issues
    
    async def _check_broken_links(self) -> List[Dict[str, Any]]:
        """
        Check for broken internal links [[Document Name]] in wiki content.
        Scans actual markdown files for [[...]] patterns.
        """
        issues = []
        
        try:
            # Get all wiki markdown files
            if not self.wiki_dir.exists():
                return issues
            
            wiki_files = list(self.wiki_dir.glob("*.md"))
            
            # Build set of existing document titles
            existing_docs = set()
            for wiki_file in wiki_files:
                doc_name = wiki_file.stem
                existing_docs.add(doc_name)
                # Also add with spaces instead of underscores
                existing_docs.add(doc_name.replace("_", " "))
            
            # Scan each file for internal links
            for wiki_file in wiki_files:
                try:
                    content = self.io.read_text(str(wiki_file))
                    
                    # Find all [[...]] patterns
                    pattern = r'\[\[([^\]]+)\]\]'
                    matches = re.findall(pattern, content)
                    
                    for link_target in matches:
                        # Normalize link target
                        normalized_target = link_target.replace(" ", "_")
                        
                        if normalized_target not in existing_docs and link_target not in existing_docs:
                            issues.append({
                                "type": "broken_internal_link",
                                "source_file": str(wiki_file),
                                "target": link_target,
                                "severity": "medium",
                                "message": f"File '{wiki_file.name}' contains broken link to '{link_target}'"
                            })
                except Exception:
                    continue
                    
        except Exception as e:
            issues.append({
                "type": "check_error",
                "severity": "high",
                "message": f"Broken links check failed: {e}"
            })
        
        return issues
    
    def find_orphans(self) -> List[str]:
        """
        Synchronous method to find orphaned documents (no backlinks).
        Returns list of document IDs with no incoming backlinks.
        """
        try:
            indexer = WikiIndexer(str(self.wiki_dir.parent))
            documents = indexer.index.get("documents", {})
            
            # Collect all documents that are referenced as backlinks
            referenced_docs = set()
            for doc_data in documents.values():
                backlinks = doc_data.get("backlinks", [])
                for backlink in backlinks:
                    target_path = Path(backlink)
                    referenced_docs.add(target_path.stem)
            
            # Find documents with no backlinks pointing to them
            orphans = []
            for doc_id in documents.keys():
                if doc_id not in referenced_docs:
                    orphans.append(doc_id)
            
            return orphans
            
        except Exception as e:
            logger = logging.getLogger(__name__)
            logger.error(f"Find orphans failed: {e}")
            return []
    
    def generate_suggestions(self, issues: List[Dict[str, Any]]) -> List[str]:
        """
        Generate actionable suggestions based on health check issues.
        Returns list of suggestion strings.
        """
        suggestions = []
        
        for issue in issues:
            issue_type = issue.get('type', '')
            doc = issue.get('document', 'unknown')
            
            if issue_type == 'orphaned_backlink':
                suggestions.append(f"Remove or fix broken backlink in '{doc}'")
            elif issue_type == 'missing_summary':
                suggestions.append(f"Add summary to document '{doc}'")
            elif issue_type == 'broken_link':
                target = issue.get('details', {}).get('broken_link', 'unknown')
                suggestions.append(f"Fix broken link [[{target}]] in '{doc}' or create the missing document")
        
        if not suggestions:
            suggestions.append("Wiki integrity is healthy - no actions needed")
        
        return suggestions
    
    def export_to_json(self, issues: List[Dict[str, Any]], output_path: str) -> bool:
        """
        Export health check results to JSON file.
        Returns True if successful, False otherwise.
        """
        try:
            from datetime import datetime
            
            export_data = {
                'timestamp': datetime.now().isoformat(),
                'total_issues': len(issues),
                'issues_by_severity': {
                    'high': len([i for i in issues if i.get('severity') == 'high']),
                    'medium': len([i for i in issues if i.get('severity') == 'medium']),
                    'low': len([i for i in issues if i.get('severity') == 'low'])
                },
                'issues': issues,
                'suggestions': self.generate_suggestions(issues)
            }
            
            self.io.write_text(output_path, json.dumps(export_data, indent=2))
            return True
            
        except Exception as e:
            logger = logging.getLogger(__name__)
            logger.error(f"Export to JSON failed: {e}")
            return False
    
    def get_stats(self) -> Dict[str, Any]:
        """
        Get health check statistics.
        Returns dict with counts of issues by type and severity.
        """
        try:
            indexer = WikiIndexer(str(self.wiki_dir.parent))
            documents = indexer.index.get("documents", {})
            
            stats = {
                'total_documents': len(documents),
                'documents_with_backlinks': 0,
                'documents_without_summaries': 0,
                'total_backlinks': 0
            }
            
            for doc_data in documents.values():
                backlinks = doc_data.get("backlinks", [])
                if backlinks:
                    stats['documents_with_backlinks'] += 1
                    stats['total_backlinks'] += len(backlinks)
                
                if not doc_data.get('summary'):
                    stats['documents_without_summaries'] += 1
            
            return stats
            
        except Exception as e:
            logger = logging.getLogger(__name__)
            logger.error(f"Get stats failed: {e}")
            return {'error': str(e)}
    
    def auto_fix_missing_summaries(self) -> int:
        """
        Auto-generate summaries for documents missing them.
        Returns count of summaries generated.
        """
        try:
            indexer = WikiIndexer(str(self.wiki_dir.parent))
            documents = indexer.index.get("documents", {})
            fixed_count = 0
            
            for doc_id, doc_data in documents.items():
                if not doc_data.get('summary'):
                    # Read document content
                    doc_path = self.wiki_dir / f"{doc_id}.md"
                    if doc_path.exists():
                        content = doc_path.read_text(encoding='utf-8')
                        # Generate simple summary (first paragraph or 200 chars)
                        first_para = content.split('\n\n')[1] if '\n\n' in content else content[:200]
                        summary = first_para[:200].strip()
                        
                        # Update index
                        indexer.index['documents'][doc_id]['summary'] = summary
                        fixed_count += 1
            
            indexer.save_index()
            return fixed_count
            
        except Exception as e:
            logger = logging.getLogger(__name__)
            logger.error(f"Auto-fix failed: {e}")
            return 0